Show informational build output by default
Siteimprove/alfa pull request #1337
Opened 2023-02-06 15:47 UTC by rcj-siteimprove

This PR is a proposal to show informational build output when running `yarn build` by default. Previously it was necessary to run `yarn build --verbose` to achieve this. The benefit is that the user can follow along and see how far the build has gotten. The drawback is that it clutters the users terminal. To opt out use the new `--quiet` flag.

2023-02-08 15:00 UTC, Jym77 requested changes
Good work. I think we can improve a bit the logic around the `minimal` flag.

2023-02-08 15:00 UTC, Jym77 commented on scripts/common/flags.js
> +  minimal: argv.minimal,
I think we should here auto-set `minimal` based on the previous two.

2023-02-08 15:08 UTC, rcj-siteimprove commented on package.json
> +    "build": "node --max-old-space-size=8192 scripts/build.js --pretty --minimal",
Yeah, let's keep it simple 👍

2023-02-08 15:21 UTC, Jym77 submitted a review, later dismissed

2023-02-09 09:42 UTC, Jym77 approved these changes

2023-02-09 09:42 UTC, merged