SIA-R10: Accept `webauthn` token
Siteimprove/alfa pull request #1339
Opened 2023-02-07 14:42 UTC by rcj-siteimprove

Resolves #1332

The rule has been updated to accept autocomplete attribute token `webauthn`.
In addition a few bugs where discovered and fixed. The bugs where:
* Attributes with modifiers like `home` followed by nothing were incorrectly passing
* Attributes with valid tokens followed by invalid tokens were incorrectly passing

2023-02-08 11:05 UTC, Jym77 requested changes

2023-02-08 11:05 UTC, Jym77 commented on packages/alfa-rules/src/sia-r10/rule.ts
> +      next = tokens[i++];
Looks like the modifier is here mandatory before a modifiable field, but shouldn't.
The grammar here should be `unmodifiable | [modifier]? modifiable`, but the code seems to accept `unmodifiable | modifier modifiable`.

2023-02-08 11:05 UTC, Jym77 commented on packages/alfa-rules/src/sia-r10/rule.ts
> + * {@link https://html.spec.whatwg.org/multipage/form-control-infrastructure.html#autofill-detail-tokens}
```suggestion
 * {@link https://html.spec.whatwg.org/multipage/#autofill-detail-tokens}
```
(shortening URL a bit, and depending less on the page structure that might change)

2023-02-08 11:05 UTC, Jym77 commented on packages/alfa-rules/test/sia-r10/rule.spec.tsx
> +  const element = <input autocomplete="section-blue shipping" />;
That should fail due to no Step 3 "either of the following to options".

2023-02-08 11:05 UTC, Jym77 commented on packages/alfa-rules/test/sia-r10/rule.spec.tsx
> +  const element = <input autocomplete="webauthn" />;
That should also fail due to the lack of mandatory field.

2023-02-13 13:43 UTC, rcj-siteimprove commented on packages/alfa-rules/test/sia-r10/rule.spec.tsx
> +test("evaluate() fails an autocomplete attribute with \`home\` followed by nothing", async (t) => {
```suggestion
test("evaluate() fails an autocomplete attribute with modifier followed by nothing", async (t) => {
```

2023-02-13 13:44 UTC, rcj-siteimprove commented on packages/alfa-rules/test/sia-r10/rule.spec.tsx
> +test("evaluate() fails an autocomplete attribute with \`home webauthn\`", async (t) => {
```suggestion
test("evaluate() fails an autocomplete attribute with modifier token followed by invalid token", async (t) => {
```

2023-02-13 14:32 UTC, Jym77 approved these changes

2023-02-13 15:52 UTC, merged