Parse` :host` pseudo-class selector
Siteimprove/alfa pull request #1352
Opened 2023-02-21 11:07 UTC by rcj-siteimprove

Resolves #1347

Updated the pseudo class parser to parse the :host selector.

2023-02-21 12:37 UTC, Jym77 requested changes
Simplifying a bit.

2023-02-21 12:37 UTC, Jym77 commented on packages/alfa-selector/src/selector.ts
> +    }
```suggestion
```
We can just remove it as [the super-class already does so](https://github.com/Siteimprove/alfa/blob/04373c2c37feafdea0c8926d7ac1d69538eee368/packages/alfa-selector/src/selector.ts#L751-L753) I do not feel the comment is adding that much given that it is a fairly common pattern we have for selectors we don't really support.

2023-02-21 12:37 UTC, Jym77 commented on packages/alfa-selector/test/selector.spec.tsx
> +  t.deepEqual(parseResult.get().toJSON(), {
```suggestion
  t.deepEqual(parse(":host").get().toJSON(), {
```
We don't really need the first test. If the test throw an exception, that's almost as good as failing. Other tests in this file seem to use this pattern.

2023-02-21 12:40 UTC, Jym77 commented
!pr help

2023-02-21 12:40 UTC, siteimprove-builduser commented
Hi there 👋 

 You have the following options: 
 - `!pr help` writes this comment
 - `!pr dedupe` Deduplicate packages
 - `!pr depgraph` Update dependency graph
 - `!pr document` Update packages documentation

2023-02-21 12:49 UTC, rcj-siteimprove commented on packages/alfa-selector/src/selector.ts
> +
```suggestion
    }
```

2023-02-21 13:36 UTC, Jym77 approved these changes

2023-02-21 13:36 UTC, rcj-siteimprove commented
!pr document

2023-02-21 13:55 UTC, Jym77 commented
!pr version

2023-02-21 13:55 UTC, Jym77 commented
!pr version

2023-02-21 13:56 UTC, Jym77 commented
!pr version

2023-02-21 14:05 UTC, Jym77 commented
!pr version

2023-02-21 14:11 UTC, Jym77 commented
!pr version

2023-02-21 14:22 UTC, Jym77 commented
!pr version

2023-02-21 14:37 UTC, Jym77 commented
!pr version

2023-02-21 14:38 UTC, Jym77 commented
!pr document

2023-02-22 08:25 UTC, Jym77 approved these changes

2023-02-22 14:00 UTC, merged