Accept serialization options in diagnostics
Siteimprove/alfa pull request #1638
Opened 2024-06-28 12:28 UTC by rcj-siteimprove

2024-06-28 13:17 UTC, rcj-siteimprove commented
!pr extract

2024-07-04 13:31 UTC, Jym77 commented
Let's go a bit back on the changes.
Instead of adding the type parameter everywhere, we can keep it on the `toJSON()` method. Also need to keep sure all properties are optionals.

```typescript
class Diagnostic {
  …
  public toJSON(options: json.SerializationOptions) { … }
}

class DiagWithNodeAndFooAndBar {
  …
  public toJSON(options: Node.SerializationOptions & Foo.SerializationOptions & Bar.SerializationOptions) { … }
```

This does, however require we also change the existing ones for consistency.

2024-07-04 15:14 UTC, rcj-siteimprove commented
!pr extract

2024-07-04 15:26 UTC, rcj-siteimprove commented
> Let's go a bit back on the changes. Instead of adding the type parameter everywhere, we can keep it on the `toJSON()` method. Also need to keep sure all properties are optionals.
> 
> ```ts
> class Diagnostic {
>   …
>   public toJSON(options: json.SerializationOptions) { … }
> }
> 
> class DiagWithNodeAndFooAndBar {
>   …
>   public toJSON(options: Node.SerializationOptions & Foo.SerializationOptions & Bar.SerializationOptions) { … }
> ```
> 
> This does, however require we also change the existing ones for consistency.

@Jym77 This should be done now

2024-07-05 08:30 UTC, Jym77 requested changes
Cleaning a few double imports, not sure why tslint messed these up 🤔

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-collection/src/collection.ts
> +import { type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import type { Comparable, Comparer, Comparison } from "@siteimprove/alfa-comparable";
```

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-list/src/list.ts
> +import { Comparable, type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import { Comparable, type Comparer, type Comparison } from "@siteimprove/alfa-comparable";
```

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-option/src/option.ts
> +import { type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import type { Comparable, Comparison } from "@siteimprove/alfa-comparable";
import { type Comparer } from "@siteimprove/alfa-comparable";
```

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-sequence/src/cons.ts
> +import { Comparable, type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import { Comparable, type Comparer, type Comparison } from "@siteimprove/alfa-comparable";
```

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-sequence/src/sequence.ts
> +import { type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import type { Comparable, type Comparer, Comparison } from "@siteimprove/alfa-comparable";
```

2024-07-05 08:30 UTC, Jym77 commented on packages/alfa-slice/src/slice.ts
> +import { Comparable, type Comparer } from "@siteimprove/alfa-comparable";
```suggestion
import { Comparable, type Comparer, type Comparison } from "@siteimprove/alfa-comparable";
```

2024-07-05 09:26 UTC, Jym77 approved these changes

2024-07-05 09:56 UTC, rcj-siteimprove commented
!pr extract

2024-07-05 11:43 UTC, Jym77 approved these changes

2024-07-05 11:49 UTC, merged