Support for `perspective` CSS property
Siteimprove/alfa pull request #1708
Opened 2024-11-05 10:07 UTC by rcj-siteimprove

CSS property `perspective` has been added.

2024-11-05 10:07 UTC, rcj-siteimprove commented
!pr extract

2024-11-05 10:11 UTC, rcj-siteimprove commented
!pr extract

2024-11-06 11:53 UTC, Jym77 requested changes
Renaming an abstraction.

2024-11-06 11:53 UTC, Jym77 commented on packages/alfa-css/src/value/transform/perspective.ts
> +  const parseLength = filter(
```suggestion
  const parseDepth = filter(
```

2024-11-06 11:53 UTC, Jym77 commented on packages/alfa-css/src/value/transform/perspective.ts
> +    CSSFunction.parse("perspective", parseLength),
```suggestion
    CSSFunction.parse("perspective", parseDepth),
```

2024-11-06 11:53 UTC, Jym77 commented on packages/alfa-css/src/value/transform/perspective.ts
> +  export const parseProp = map(parseLength, (depth) => Perspective.of(depth));
```suggestion
  export const parseProp = map(parseDepth, Perspective.of);
```

2024-11-07 10:11 UTC, Jym77 approved these changes

2024-11-07 12:45 UTC, merged