Make objects with browsing context container focusable
Siteimprove/alfa pull request #399
Opened 2020-09-18 12:57 UTC by Jym77

Closes #388.

2020-09-18 12:57 UTC, Jym77 commented on packages/alfa-rules/test/sia-r63/rule.spec.tsx
> +  // const target = <object>{h.document(["Some nested document"])}</object>;
And we already need #398 😁

2020-09-18 13:27 UTC, kasperisager requested changes

2020-09-18 13:27 UTC, kasperisager commented on packages/alfa-dom/src/node/element.ts
> +
```suggestion
```

2020-09-18 13:27 UTC, kasperisager commented on packages/alfa-rules/test/sia-r63/rule.spec.tsx
> +  target._attachContent(h.document(["Some nested document"]));
This is a package internal API which shouldn't be used so let's wait for #398.

2020-09-22 06:47 UTC, kasperisager commented on packages/alfa-rules/test/sia-r63/rule.spec.tsx
> +  // const target = <object>{h.document(["Some nested document"])}</object>;
All set 👍

2020-09-22 07:52 UTC, kasperisager requested changes
Looks good! 💯 Just a minor re-arrangement of some imports.

2020-09-22 07:52 UTC, kasperisager commented on packages/alfa-rules/test/sia-r63/rule.spec.tsx
> +import { Document, h } from "@siteimprove/alfa-dom";
```suggestion
import { h } from "@siteimprove/alfa-dom/h";
import { jsx } from "@siteimprove/alfa-dom/jsx";
import { test } from "@siteimprove/alfa-test";

import { Document } from "@siteimprove/alfa-dom";
```

2020-09-22 09:42 UTC, kasperisager approved these changes

2020-09-22 09:49 UTC, merged