Support `font` shorthand property
Siteimprove/alfa pull request #693
Opened 2021-02-08 14:36 UTC by Jym77

Resolves #682 

(this is major change due to the changes in `Parser.tee`)

2021-02-08 14:52 UTC, Jym77 commented
Arf, need more heavy handed work to handle `font-style`… (or maybe just ignore the extra angle due to poor browser support).

2021-02-09 09:01 UTC, kasperisager submitted a review, later dismissed

2021-02-09 09:36 UTC, kasperisager requested changes

2021-02-09 09:36 UTC, kasperisager commented on packages/alfa-css/src/value/keyword.ts
> +        Keyword.of(ident.value.toLowerCase()) as ToKeyword<T>
I'm not too keen on this as the difference between `Keyword<"foo" | "bar">` and `Keyword.ToKeyword<"foo" | "bar">` is too small, especially when broken over several lines. The former type is incorrect and the latter will result in a correct type being produced, but all it takes is forgetting `.ToKeyword` for the type to end up wrong. It's much easier to tell `Keyword<"foo"> | Keyword<"bar">` from `Keyword<"foo" | "bar">`, even if it does cost some additional keystrokes. Correctness over conciseness though 😄

2021-02-09 09:39 UTC, kasperisager commented on packages/alfa-css/src/value/percentage.ts
> +    return `${this._value * 100}%`;
👏

2021-02-09 10:07 UTC, kasperisager submitted a review, later dismissed

2021-02-09 10:07 UTC, kasperisager commented on packages/alfa-css/src/value/keyword.ts
> +  export function parse<T extends string>(...keywords: ReadonlyArray<T>) {
```suggestion
  export function parse<T extends string>(...keywords: Array<T>) {
```

The arrays created for argument spreads are internal to the function and so there's no risk of the caller passing a mutable array that is also mutable by the function:

```js
const f = (...a) => a;
const a = [1, 2, 3];

f(...a) !== a;
f.apply(this, a) !== a;
```

2021-02-09 10:42 UTC, kasperisager approved these changes
Looks great! 🎉

2021-02-09 10:53 UTC, merged