Update: is_clipped
Siteimprove/alfa pull request #827
Opened 2021-06-08 12:14 UTC by elenamongelli

Resolves #

2021-06-08 12:30 UTC, Jym77 requested changes

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/src/common/predicate/is-clipped.ts
> +              if (dimension.value <= 1) {
If this case, we need <=0. If the height/width is 1 pixel big, it is visible (not much, but still…)
```suggestion
              if (dimension.value <= 0) {
```

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/src/common/predicate/is-clipped.ts
> +      }
We can probably merge both cases and avoid duplicating the rest of the logic:
`if (x.value === "auto" || x.value === "scroll" || y.value === "auto" || y.value === "scroll")`

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/src/common/predicate/is-clipped.ts
> +        const { value: width } = style.computed("width");
Also, since `height` and `width` are used in several places (also in the `"hidden"` case), we can refactor the definitions out of the `if`.

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
> +  );
That one is indeed not needed since it is already covered by the previous tests.
```suggestion
```

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
> +test(`isVisible() returns false when an element is scroll and its size is 0x0 px`, (t) => {
```suggestion
test(`isVisible() returns false when an element scrolls its overflow and its size is reduced to 0 pixel, thus hidding the scrollbar`, (t) => {
```
(similar for the `auto` case)

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
> +    <div style={{ width: "0px", height: "0px", overflow: "scroll" }}>
That should probably be split in several cases for each dimension just like https://github.com/Siteimprove/alfa/blob/develop/packages/alfa-rules/test/common/predicate/is-visible.spec.tsx#L34-L51 to show that individual dimensions of 0 are enough (it's not about having **both** height and width at 0)

(same for the `auto` case)

2021-06-08 12:30 UTC, Jym77 commented on packages/alfa-rules/test/common/predicate/is-visible.spec.tsx
> +});
```suggestion
```
Looks like a duplicate.

2021-06-09 13:22 UTC, Jym77 submitted a review, later dismissed

2021-06-14 09:07 UTC, kasperisager commented
@Jym77 or @elenamongelli: Could one of you update the title to be a little more descriptive of what the changes involve?

2021-06-16 10:00 UTC, kasperisager approved these changes

2021-06-16 11:01 UTC, merged