Implement SIA-R79
Siteimprove/alfa pull request #869
Opened 2021-07-20 11:09 UTC by elenamongelli

Resolves #852

2021-07-20 11:45 UTC, Jym77 requested changes
Great work!
Some typo corrections.

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  uri: "https://alfa.siteimprove.com/rules/sia-r80",
```suggestion
  uri: "https://alfa.siteimprove.com/rules/sia-r79",
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  requirements: [Criterion.of("1.4.8")],
```suggestion
```
That rule doesn't map to WCAG.

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +                () => Outcomes.IsNotVisibleAndNoHidden
```suggestion
                () => Outcomes.IsNotVisibleAndNotHidden
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  export const IsNotVisibleAndNoHidden = Err.of(
```suggestion
  export const IsNotVisibleAndNotHidden = Err.of(
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  export const IsDescedant = Ok.of(
```suggestion
  export const IsDescendant = Ok.of(
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +            () => Outcomes.IsDescedant,
```suggestion
            () => Outcomes.IsDescendant,
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +            () => Outcomes.IsNotDescedant
```suggestion
            () => Outcomes.IsNotDescendant
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  export const IsNotDescedant = Err.of(
```suggestion
  export const IsNotDescendant = Err.of(
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +      `The target element is a figure descedant, or every visible text node descedants are descedant themselves of the target element and are a <code>, <kbd> or <samp> element.`
```suggestion
      `The target element either has a <figure> ancestor, or all its text is inside <code>, <kbd> or <samp> elements.`
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +      `The element is not a figure descedant and there aren't visible text node descendant which are descedant themselves of the target element and are a <code>, <kbd> or <samp> element. `
```suggestion
      `The element has no <figure> ancestor and has text which not inside a <code>, <kbd> or <samp> element. `
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +function isGood(device: Device): Predicate<Node> {
```suggestion
function hasTextInsideAllowedElements(device: Device): Predicate<Node> {
```

2021-07-20 11:45 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +              .some(hasName("figure")) || isGood(device)(target),
```suggestion
              .some(hasName("figure")) || hasTextInsideAllowedElements(device)(target),
```

2021-07-21 10:28 UTC, Jym77 requested changes
Small typo.
Plus need to run `yarn document`.

2021-07-21 10:28 UTC, Jym77 commented on packages/alfa-rules/src/sia-r79/rule.ts
> +import { Predicate } from "@siteimprove/alfa-predicate";
That one should move up with the rest of the global `import`.

2021-08-23 10:47 UTC, kasperisager requested changes

2021-08-23 10:47 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +                  ),
```suggestion
                  .some(hasAttribute("aria-hidden", equals("true")),
```

2021-08-23 10:47 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  };
Can this be expressed as a predicate applied over `node.descendants()`?

2021-08-24 10:24 UTC, kasperisager submitted a review, later dismissed
Looks great! Just some small clarifications to the comments and some dead-code removal.

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +  return function isNodeAllowed(node: Node): boolean {
```suggestion
  return function hasOnlyAllowedText(node): boolean {
```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +      .every(isNodeAllowed);
```suggestion
      .every(hasOnlyAllowedText);
```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +    }
```suggestion
    // Any text within these elements is allowed and so we can stop recursing
    // when we encounter them.
    if (and(isElement, hasName("code", "kbd", "samp"))(node)) {
      return true;
    }

```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +    }
```suggestion
    // If we encounter a visible text node that isn't within one of the previous
    // elements then the text is not allowed.
    if (and(isText, isVisible(device))(node)) {
      return false;
    }

```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +    // else the function goes deeper in the tree checking the children
```suggestion
    // Otherwise, recursively check that the children only have allowed text.
```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +
```suggestion
```

2021-08-24 10:24 UTC, kasperisager commented on packages/alfa-rules/src/sia-r79/rule.ts
> +//import { Set } from "@siteimprove/alfa-set";
```suggestion
```

2021-08-25 06:20 UTC, kasperisager approved these changes

2021-09-02 13:51 UTC, kasperisager approved these changes

2021-09-03 07:00 UTC, merged