Implements SIA-Rule 77
Siteimprove/alfa pull request #923
Opened 2021-09-14 14:29 UTC by elenamongelli

Resolves #841

2021-09-20 07:38 UTC, Jym77 requested changes

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r46/rule.ts
>          for (const table of tables) {
```suggestion

        for (const table of tables) {
```
Let's keep those empty lines.

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r46/rule.ts
>            const headers = table
```suggestion

          const headers = table
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r46/rule.ts
>            for (const header of headers) {
```suggestion

          for (const header of headers) {
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r46/rule.ts
>                  hasRole(device, (role) => role.is("cell"))(cell.element) &&
```suggestion
                // Does there exists a cell with the target as one of its headers?
                hasRole(device, (role) => role.is("cell"))(cell.element) &&
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +  requirements: [Criterion.of("1.3.1"), Technique.of("H43")],
```suggestion
  requirements: [Criterion.of("1.3.1")],
```
This rule is not related to H43.

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +          );
```suggestion
          );
          
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +          const model = Table.from(table);
```suggestion
          const model = Table.from(table);
          
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +            );
```suggestion
            );
            
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +    const data = new Map<Element, [cell: Cell, table: Table]>();
```suggestion
    const data = Map.empty<Element, Cell>();
```
Since the table is not re-used in the expectation, no need to store it.

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +import { Predicate } from "@siteimprove/alfa-predicate";
```suggestion
import { Map } from "@siteimprove/alfa-map";
import { Predicate } from "@siteimprove/alfa-predicate";
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +              data.set(dataCell, [cell, model]);
```suggestion
              data.set(dataCell, cell);
```

2021-09-20 07:38 UTC, Jym77 commented on packages/alfa-rules/src/sia-r77/rule.ts
> +        const [dataCell] = data.get(target)!;
```suggestion
        const dataCell = data.get(target)!;
```
And we should likely call that variable `cell` to keep the same naming convention as in Applicability (`dataCell` = the `<td>` element, `cell` = the `Cell` (concept) inside the table (concept).

2021-09-27 14:13 UTC, Jym77 submitted a review, later dismissed

2021-09-29 13:22 UTC, Jym77 approved these changes

2021-09-30 11:37 UTC, kasperisager approved these changes

2021-09-30 11:53 UTC, merged